### ISSUE TITLE
☄ IiifPrint x Valkyrie Epic (Copy)

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#145]
This is a clone of: 
- https://github.com/scientist-softserv/iiif_print/issues/312

Valkyrize IiifPrint. It should work with both valkyrie and active fedora applications. 

## Tasks

Consider adding listeners to mimic active record call backs: 

https://assaydepot.slack.com/archives/C0313NKG2DA/p1704392246521249
- [ ] https://github.com/scientist-softserv/iiif_print/issues/314
- [x] https://github.com/scientist-softserv/iiif_print/issues/316
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/84 (what)
- [ ] https://github.com/scientist-softserv/hykuup_knapsack/issues/99 (when - listens for when to execute the what)
- [ ] https://github.com/scientist-softserv/iiif_print/issues/325

## NOTES
- [callbacks](https://github.com/samvera-labs/transitioning-to-valkyrie-workshop#legacy-callbacks)
