### ISSUE TITLE
☄ CollectionResources x Thumbnails

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#238]
# Summary 

Collection Branding tab allows the user to upload a banner, logo and thumbnail and supports alt text for each. The Alt Text isn't working correctly. 

## Tasks

- [x] #237
- [x] #214
- [x] #205 

# Acceptance Criteria

- [ ] A user should be able to upload a thumbnail to a collection, from the collection edit page
- [ ] Collections should have thumbnails
- [ ] rake task should transfer active fedora collections into resources and keep their thumbnail

# Screenshots or Video
 collections can no longer upload a thumbnail. After creating a collection, a user used to be able to upload a thumbnail on edit.

![image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/880d0ab3-a883-43c8-b0bd-1c7fc3c842ed)

It should look like:

![image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/9649216f-6466-4b30-af8c-37b08446f689)

# Testing Instructions

On [DEMO](https://demo.hyku-demo.notch8.cloud), Login as admin

- [ ] Create a New User Collection
- [ ] After clicking save, the edit page should have a "Branding" tab. Click it, and notice the "Thumbnail" section at the bottom of the form
- [ ] Upload an image and save. Note, Alt Text may look out of place - this is a known bug and considered a separate issue. Alt text is optional - enter it if you'd like. 
- [ ] Click Collections in the sidebar to view all the collections (index page)
- [ ] The thumbnail should appear and match the file you just uploaded
- [ ] If you entered alt text, you should see if when you inspect the thumbnail element of that page. ie: see eddie-baby-alt-text

<img width="703" alt="image" src="https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/3f855b71-dd43-489e-8cba-c594414b6f2b">

# Notes

ref: 
-  https://github.com/samvera/hyrax/issues/5286
