### ISSUE TITLE
☄️  Epic 3: Move HykuUp to Valkyrie

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/hykuup_knapsack#33]
# Summary

# Dependent on

- https://github.com/scientist-softserv/adventist_knapsack/issues/112
- https://github.com/scientist-softserv/hykuup_knapsack/issues/32

# Tasks

- [x] #35 
- [ ] Update hyku submodule on hykuup_knapsack
- [x] #34 
- [ ] Address the data models
- [ ] Localized testing (e.g. no data from HykuUp proper)
- [ ] Note: we’ll need to hornswoggle some ActiveFedora baseed data in to test the “double combo” approach.
- [ ] Integration testing
- [ ] Data “migration” plan to execute

## NOTES

GBH Valkyrie: 
- https://github.com/scientist-softserv/ams/issues/20
- https://github.com/scientist-softserv/ams/issues/19
- bulrkax: hyrax-4-valkyrie-support
- hyrax: hyrax-4-valkyrie-support
- rails: 6
- breakdown: https://jamboard.google.com/d/1a0WjBjPGYCxFEqJmN2jJj0oXqVx89Xq9jUhHv41KV8U/viewer

**Comment by jillpe** [comment]
Blocked by Epic 1 and 2
