### ISSUE TITLE
🦄 Make fileset / file migration work in Frejya

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/hykuup_knapsack#34]
## Summary
- ~make file set file migration work in valkyrie/hyrax (don't think we need an upgrade - we can work on hyrax adapter in dassie just fine. Find/use Rob's valkyrie branch)~
- ~Rob recommends using GBH since they have the dev environment already set up for this.~

UPDATE: 

We are already in a state where we can attach filesets to a valkyrie resource, however, we have not dealt with pre-existing active fedora based file sets. 

This ticket is to handle the migration of active fedora file sets to resources file sets. 

## Tasks/Acceptance Criteria
- [ ] git checkout main. Create several active fedora objects with file sets attached.
- [ ] switch to i35-valkyrize-hyku branch. 
- [ ] Ensure those files are loading and still accessible
