### ISSUE TITLE
☄ EPIC: HYKU test plan: Test that everything works

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#48]
# Summary

Go through a copy of the Hyku test plan. It will be outdated (2022) so it may also need to be updated to reflect some changes. Doing so will help our future selves/releases too.

- [ ] Test Plan against v6.0.0rc1
  - #96 
- [ ] Test Plan (limited) again v6.0.0rc2
  - #97 
  - update plan with new features from pals
- [ ] Test Plan against v6.0.0 
  - https://github.com/scientist-softserv/hykuup_knapsack/issues/113

UPDATE: 

We decided to merge in pals contributions. Please note the diffs you see when evaluating the test plan. The diffs are likely new features of hyku and we can use them to update the hyku test plan. The test plan will commence from v6.0.0rc2.

# Acceptance Criteria

  - [ ] Make bug tickets if there are any issues

## TODOS

- [x] #72
  - [x] Global Index / Institution List Page	4
  - [x] Global Administrator / User Login Page	6
  - [ ] Global Sign Up Page	7
  - [ ] Global Forgot your Password? Page	8
  - [ ] Change your password page	9
  - [x] Global Tenant Accounts Index Page (Admin only)	10
  - [x] Global Tenant Account New Page (Admin only)	11
  - [x] Global Tenant Account Manage Page (Admin only)	12
  - [x] Global Tenant Account Edit Page (Admin only)	13
  - [ ] Global Users Index Page (Admin only)	14
  - [ ] Global Users New Page (Admin only)	15
  - [ ] Global Users Manage Page (Admin only)	16
  - [ ] Global Users Edit Page (Admin only)	17

- [x] #73
  - [ ] Homepage *	18
  - [ ] Contact Page *	19
  - [ ] Catalog (Search Results) Page	20
  - [ ] Collection Show Page	21
  - [ ] Work Show Page	22
  - [ ] FileSet Show Page	23
  - [ ] Dashboard Page	24
  - [ ] Dashboard Page (Admin)	25
  - [ ] [Pro](https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.j7man6ygm6zv)file Page	27
  - [ ] Profile Edit Page	[28](https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.j7man6ygm6zv)
  - [ ] Notifications Page	29
  - [ ] Transfers Page	30
  - [ ] Manage Proxies Page	31
  - [ ] Workflow Roles Page	85

- [x] #74
  - [ ] Dashboard My Collections Index Page	32
  - [ ] Dashboard Collection New Page	33
  - [ ] Dashboard Collection Edit Page	34
    - [ ] Description	34
    - [ ] Branding (User Collection only)	35
    - [ ] Discovery (User Collection only)	36
    - [ ] Sharing	37
  - [ ] Dashboard Collection Show Page	38

- [x] #75
  - [ ] Dashboard My Works Index Page	39
    - [ ] Dashboard Works New by Batch Page	40
      - [ ] Files	40
      - [ ] Descriptions	41
      - [ ] Relationships	42
      - [ ] Sharing	43
    - [ ] Dashboard Work New Page	44
      - [ ] Descriptions	44
      - [ ] Files	45
      - [ ] Relationships	46
      - [ ] Sharing	47
    - [ ] Dashboard Work Edit Page	48
      - [ ] Descriptions	48
      - [ ] Files	49
      - [ ] Relationships	50
      - [ ] Sharing	51
    - [ ] Review Submissions Page	52
      - [ ] Under Review	52
      - [ ] Published	53

- [x] #76
  - [ ] Manage Users Page	54
  - [ ] Manage Groups Index Page	55
  - [ ] Manage Groups New Page	56
  - [ ] Manage Groups Edit Page	57
    - [ ] Description	57
    - [ ] Users	58
    - [ ] Remove	59
  - [ ] Manage Embargoes Index Page	60
    - [ ] All Active Embargoes	60
    - [ ] Expired Active Embargoes	61
    - [ ] Deactivated Embargoes	62
  - [ ] Manage Embargoes Edit Page	63
  - [ ] Manage Embargoes Deactivate Page	64
  - [ ] Manage Leases Index Page	65
    - [ ] All Active Leases	65
    - [ ] Expired Active Leases	66
    - [ ] Deactivated Leases	67
  - [ ] Manage Leases Edit Page	68
  - [ ] Manage Leases Deactivate Page	69

- [x] #77
  - [ ] Settings → Labels PageSettings → Labels Page	70
  - [ ] Settings → Appearance Page	71
    - [ ] Logo / Banner Image	71
    - [ ] Default Images	72
    - [ ] Colors	73
    - [ ] Fonts	74
    - [ ] Custom CSS	75
  - [ ] Settings → Collection Types Index Page	76
  - [ ] Settings → Collection Types New Page	77
  - [ ] Settings → Collection Types Edit Page	78
    - [ ] Description	78
    - [ ] Settings	79
    - [ ] Participants	80
    - [ ] Badge Color	81
  - [ ] Settings → Pages Page	82
  - [ ] Settings → Content Block	83
  - [ ] Settings → Features Page	84

- [ ] #104

## Notes

Hyrax TEST PLANS: 
- (based off of [4.0.0rc2](https://docs.google.com/spreadsheets/d/1TV2183bh-DHMEBn2idc-foFITKbS_bLV/edit#gid=426373554) - may need to be updated) - https://docs.google.com/spreadsheets/d/1BxpqCPUUFk0J2j12umRQw6GKbUcQ8dmL/edit#gid=1996559587
- testing Sirenia (Hyrax 5.0.0rc2 Valkyrie/Fedora) https://docs.google.com/spreadsheets/d/1cBmqnbwWvpKLPOehpKBzuPZo1W1dYo7Y/edit#gid=426373554

- [ ] Copy of [HYKU test plan ](https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.rifwygk2508n)
- [ ] PALS [Groups Feature](https://docs.google.com/document/d/1ptCu3dlrZI14F3RwiiUbtrA8a1R7YEwwt1WnP-GBvvY/edit#heading=h.rifwygk2508n)

**Comment by ShanaLMoore** [comment]
blocked by #78

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/

**Comment by jillpe** [comment]
https://github.com/scientist-softserv/palni-palci/issues/903
- good place to start for the differences

**Comment by ShanaLMoore** [comment]
due to limited resources, we will test and fix the valkyrized version instead
