### ISSUE TITLE
☄ EPIC 4: Update HykuUP Knapsack with Valkyrized Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#49]
## ❗ Before deploying to prod ❗ 

The following task must be completed first:
- https://github.com/scientist-softserv/dev-ops/issues/788

Depends on 
- #35 

## Tasks

1. Point HykuUp Knapsack's gitmodule to i35-valkyrize-hyku. Q: Is there any reason we shouldn't update [knapsack prime](https://github.com/samvera-labs/hyku_knapsack)? 

## Acceptance Criteria

- [ ] HykuUp Knapsack is deployed and running off of a valkyrized hyku

### Notes (old)
- [ ] Address the data models
- [ ] Localized testing (e.g. no data from HykuUp proper)
- [ ] Note: we’ll need to hornswoggle some ActiveFedora baseed data in to test the “double combo” approach.
- [ ] Integration testing
- [ ] Data “migration” plan to execute (for any existing clients)
