### ISSUE TITLE
☄ EPIC - Upgrade Hyku

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#65]
# Summary
Upgrade Hyku

# Tasks

- [x] merge in adventist_dev contributions
- [ ] merge in pals contributions (separate release)
  - https://github.com/scientist-softserv/palni-palci/issues/903
  - https://github.com/samvera/hyku/pull/2061

## Get the app to boot with the following upgrades: 
- [x] #36
- [x] #37
  - [x] Upgrade to blacklight 7 (comes with Hyrax upgrade)
- [x] #38
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/51
- [x] #55 

## Divide and Conquer: 
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] https://github.com/scientist-softserv/hykuup_knapsack/issues/50
- [x] #48

## NOTES

Overview of Steps per Jeremy's [slack convo](https://assaydepot.slack.com/archives/C0313NKG2DA/p1702492378741979):
-   [X] Get Hyku booting on Rails 6, Hyrax 5, Ruby 3.2 into hyrax-5-upgrade
-   [X] Get adventist_dev specs passings
-   [x] Merge adventist_dev into hyrax-5-upgrade
-   [x] Work on hyrax-5-upgrade branch
    -   [x] Get specs passing
    -   [ ] [Incorporate Pals contribute back tickets](https://github.com/samvera/hyku/pull/2061)
      - Do we need a staging environment?
    -   [ ] If applicable, keep in-sync with adventist_dev updates
-   [ ] Exercise Hyku test plan on hyrax-5-upgrade branch
-   [ ] Merge hyrax-5-upgrade into main

**Comment by ShanaLMoore** [comment]
TODO: is there a hyku test plan?
