### ISSUE TITLE
GLOBAL Hyku Test Plan

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#72]
# Summary 

Focus on reviewing the test plan for the GLOBAL section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks

  - [ ] Global Index / Institution List Page	4
  - [ ] Global Administrator / User Login Page	6
  - [ ] Global Sign Up Page	7
  - [ ] Global Forgot your Password? Page	8
  - [ ] Change your password page	9
  - [ ] Global Tenant Accounts Index Page (Admin only)	10
  - [ ] Global Tenant Account New Page (Admin only)	11
  - [ ] Global Tenant Account Manage Page (Admin only)	12
  - [ ] Global Tenant Account Edit Page (Admin only)	13
  - [ ] Global Users Index Page (Admin only)	14
  - [ ] Global Users New Page (Admin only)	15
  - [ ] Global Users Manage Page (Admin only)	16
  - [ ] Global Users Edit Page (Admin only)	17
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

Use [DEMO](https://valkyrie.hyku-demo.notch8.cloud/)

pop up? => samvera/hyku

![Image](https://github.com/scientist-softserv/hykuup_knapsack/assets/10081604/451388bf-da82-41be-9ab0-6a50e92a9d30)

login should be in 1password ATLA HYKU.

---

## Global Index / Institution List Page

![image4](https://github.com/samvera/hyku/assets/19597776/4e6c6681-39e3-491a-ab7d-64f995d775b4)

### As a non-signed in user:

- [ ] I can see a list of each institution
  - [ ] Each institution has a display of their theme logo (or a placeholder if there is no logo)
  - [ ] I can click on the link for each institution, which directs me to the tenant for that institution
- [ ] I can click on the link to Administrator login (in the footer), which directs me to the Log in form
- [ ] I can select my preferred language from the Language dropdown menu
  - [ ] Selecting a language only sets the language for the current site, not for each of the individual tenants

![image39](https://github.com/samvera/hyku/assets/19597776/005910e7-8fbd-4c27-a9d4-a6cc07f34820)

### As a signed-in administrator:

- [ ] I can see a list of each institution
  - [ ] Each institution has a display of their theme logo (or a placeholder if there is no logo)
  - [ ] I can click on the link for each institution, which directs me to the tenant for that institution
- [ ] I can click Logout, which logs me out and directs me back to the Global Index page
- [ ] I can select my preferred language from the Language dropdown menu
  - [ ] Selecting a language only sets the language for the current site, not for each of the individual tenants
- [ ] I can click on Accounts, which directs me to the Accounts page for the tenants
- [ ] I can click on Users, which directs me to the Manage Users page for the users

## Global Administrator / User Login Page

![image55](https://github.com/samvera/hyku/assets/19597776/6f43db4a-8a11-457a-91b7-28004ba864ab)

- [ ] I can see a form to enter an email and password
  - [ ] The form validates the format of my email
  - [ ] The form will only submit successfully if my account already exists
- [ ] I can check/uncheck a Remember me box
  - [ ] When this box is checked, my username will be saved on the form the next time I log in
- [ ] I can click Log in, which logs me in and directs me to the Global Index page
- [ ] I can click on the link to Sign up, which directs me to the Create a new account form
- [ ] I can click on the link to Forgot your password?, which directs me to the Forgot your password? form

## Global Sign Up Page

![image24](https://github.com/samvera/hyku/assets/19597776/c61751bc-f91d-4c79-847a-e780264ab3d6)

### As a user:

- [ ] I can see a form to Create a new account that validates the following inputs:
  - [ ] Your Name
  - [ ] Email Address
  - [ ] Password
  - [ ] Password confirmation
  - [ ] The form will not submit if any of the inputs is missing or invalid
- [ ] I can click Create account, which registers me as a new user and directs me to the Global Index page
- [ ] I can click on the link to Log in, which directs me to the Log in form
- [ ] I can click on the link to Forgot your password?, which directs me to the Forgot your password? form
- [ ] I can click on the link to Administrator login (in the footer), which directs me to the Log in form

## Global Forgot your Password? Page

![image32](https://github.com/samvera/hyku/assets/19597776/178e82b8-8643-4abb-b82f-3e5b51abd772)

### As a user:

- [ ] I can see a form with an input for my Email
  - [ ] The form will not submit if the Email is empty or improperly formatted
  - [ ] The form will only submit if an account with my email already exists
- [ ] I can click Send me reset password instructions, which sends me an email with instructions for resetting my password
  - [ ] When I receive my password reset email, I can click on the link to “Change my password”, which directs me to the Change your password form
    * Found in [https://mailtrap.io/inboxes](https://mailtrap.io/inboxes)
- [ ] I can click on the link to Log in, which directs me to the Log in form
- [ ] I can click on the link to Sign up, which directs me to the Create your account form
- [ ] I can click on the link to Administrator login (in the footer), which directs me to the Log in form

## Change your password page

![image5](https://github.com/samvera/hyku/assets/19597776/708604aa-814b-4bd1-a5ce-834696315ea1)

### As a user:

- [ ] I can see a form to change my password
  - [ ] There is a field for New password
  - [ ] There is a field for Confirm new password
  - [ ] The form will not submit if the password is too short or if the password fields do not match
- [ ] I can click Change my password, which sets my new password and directs me to the Global Index page
- [ ] I can click on the link to Log in, which directs me to the Log in form
- [ ] I can click on the link to Sign up, which directs me to the Create your account form
- [ ] I can click on the link to Administrator login (in the footer), which directs me to the Log in form

## Global Tenant Accounts Index Page (Admin only)

![image15](https://github.com/samvera/hyku/assets/19597776/7f70f45f-dddf-4a40-9583-d71f664294b0)

### As a user:

- [ ] If I try to access this page (as a non logged-in admin), I am redirected to the Log in page with a flash message saying “You are not authorized to access this page.”
### As an admin:

- [ ] I can see a table listing all of the tenant accounts, including their:
  - [ ] UUID
  - [ ] Cname
  - [ ] Actions (Manage, Edit, Delete)
    - [ ] I can click Manage, which directs me to the Manage Account page
    - [ ] I can click Edit, which directs me to the Editing Account form
    - [ ] I can click Delete, which removes that tenant account
- [ ] I can filter through the tenant accounts using the search bar
- [ ] I can click Create a new account, which directs me to the Create a new repository form

## Global Tenant Account New Page (Admin only)

![image62](https://github.com/samvera/hyku/assets/19597776/d6cbb942-4d04-4f59-a5d6-53a1476ded28)

### As an admin:

- [ ] I can see a form to create a new tenant account
  - [ ] There is a field for Short name (Cname)
  - [ ] The form will not submit if the input is empty or invalid
- [ ] I can click Save, which saves the new tenant and directs me to the Manage Account form
- [ ] I can click on the link to Cancel, which directs me back to the tenant Accounts page

## Global Tenant Account Manage Page (Admin only)

![image23](https://github.com/samvera/hyku/assets/19597776/126e80b6-bfb9-4ab0-9c19-8a2e26d45f90)

### As an admin:

- [ ] I can see the Cname of the tenant account I selected to manage
- [ ] I can click Edit Account, which directs me to the Editing Account form
- [ ] I can see a form to invite new administrators to this specific tenant account via email
  - [ ] The form will not submit if the input is empty or invalid
  - [ ] The entered email does **not** have to be linked to an existing account in order to be submitted successfully
  - [ ] I can click Add, which adds the user to the list of Current Account Administrators
- [ ] I can click Cancel, which directs me to the tenant Accounts page
- [ ] I can see a list of admin users for that tenant account under the Current Account Administrators tab
  - [ ] I can click Remove, which removes the admin user from that tenant
- [ ] I can see a list of all users under the All Users tab
  - [ ] I can click Add, which adds the user to the Current Account Administrators

## Global Tenant Account Edit Page (Admin only)

![image3](https://github.com/samvera/hyku/assets/19597776/fd1c45fd-b3a0-453a-add4-a29f5c41b96b)

### As an admin:

- [ ] I can check/uncheck a box for Is public
  - [ ] When this box is checked, the tenant is visible to the public from the Global Index page
- [ ] I can see a form that contains the following attributes (and corresponding values) of the selected Tenant account:
  - [ ] Tenant UUID (**Non-modifiable**) (required)
  - [ ] Tenant CNAME (required)
  - [ ] Solr Endpoint URL
  - [ ] Fedora Endpoint URL
  - [ ] Fedora Endpoint Base Path
- [ ] I can click Save changes, which saves my changes and directs me to the Manage Account page
- [ ] I can click Cancel, which directs me to the tenant Accounts page

## Global Users Index Page (Admin only)

![image81](https://github.com/samvera/hyku/assets/19597776/d237def8-78bf-4d1f-b307-4aaa3c5c45c1)

### As an admin:

- [ ] I can see a table listing all users across all tenants
- [ ] The following attributes of each user are displayed in separate columns:
  - [ ] Email
  - [ ] Display name
  - [ ] Department
  - [ ] Title
  - [ ] Affiliation
  - [ ] Superadmin
  - [ ] Actions (Manage, Edit, Become, Delete)
    - [ ] I can click Manage, which directs me to the Manage User page
    - [ ] I can click Edit, which directs me to the Edit User form
    - [ ] I can click Become, which signs me out of my account and into the account of that user
    - [ ] I can click Delete, which removes that user
- [ ] I can filter through users using the search box
- [ ] I can click Create New, directing me to the Create a new user form

## Global Users New Page (Admin only)

![image40](https://github.com/samvera/hyku/assets/19597776/01dc1c7c-5eef-4eb9-80d7-2e8d9b8abb32)

### As an admin:

- [ ] I see a form where I can assign attributes and create a new user
  - [ ] The form will fail to submit if any of the entered attributes are invalid
- [ ] I can click Save, which saves the new user and directs me back to the Manage Users page
- [ ] I can click Cancel, which directs me back to the Manage Users page

## Global Users Manage Page (Admin only)

![image10](https://github.com/samvera/hyku/assets/19597776/b4e9e8c6-1a10-486c-be8a-416275ec4f5d)

### As an admin:

- [ ] I can check the box to assign/unassign the superadmin role
  - [ ] When this box is checked, the user has the privileges of a superadmin
- [ ] I can click Update, which saves the changes and directs me back to the Manage Users page
- [ ] I can click Cancel, which directs me back to the Manage Users page
- [ ] I can click Edit, which directs me to the Edit User form

## Global Users Edit Page (Admin only)

![image73](https://github.com/samvera/hyku/assets/19597776/607553e1-f02c-4de3-a5fb-af5bd68ccf4a)

### As an admin:

- [ ] I can see a form to edit attributes of the selected user
  - [ ] Display Name is filled in
  - [ ] Email address is filled in
- [ ] I can click Save changes, which saves my changes and directs me back to the Manage Users page
- [ ] I can click Cancel, directing me back to the Manage Users page

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/

**Comment by ShanaLMoore** [comment]
due to limited resources, we will test and fix the valkyrized version instead
