### ISSUE TITLE
INDIVIDUAL PAGES Hyku Test Plan v6.0.0rc1

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#73]
# Summary 

Focus on reviewing the test plan for the INDIVIDUAL PAGES section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks
  - [ ] Homepage *	18
  - [ ] Contact Page *	19
  - [ ] Catalog (Search Results) Page	20
  - [ ] Collection Show Page	21
  - [ ] Work Show Page	22
  - [ ] FileSet Show Page	23
  - [ ] Dashboard Page	24
  - [ ] Dashboard Page (Admin)	25
  - [ ] [Pro](https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.j7man6ygm6zv)file Page	27
  - [ ] Profile Edit Page	[28](https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.j7man6ygm6zv)
  - [ ] Notifications Page	29
  - [ ] Transfers Page	30
  - [ ] Manage Proxies Page	31
  - [ ] Workflow Roles Page	85
  
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/

**Comment by ShanaLMoore** [comment]
due to limited resources, we will test and fix the valkyrized version instead
