### ISSUE TITLE
DASHBOARD COLLECTIONS Hyku Test Plan v6.0.0rc1

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#74]
# Summary 

Focus on reviewing the test plan for the DASHBOARD COLLECTIONS section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks
  - [x] Dashboard My Collections Index Page	32
  - [x] Dashboard Collection New Page	33
  - [ ] [Dashboard Collection Edit Page](https://github.com/scientist-softserv/hykuup_knapsack/issues/74#issuecomment-1876137567)	34 ❌ **(TODO: Retest once deployed to staging)**
    - [ ] Description	34
    - [ ] Branding (User Collection only)	35
    - [ ] Discovery (User Collection only)	36
    - [ ] Sharing	37
  - [ ] Dashboard Collection Show Page	38
  
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

**Comment by ShanaLMoore** [comment]
Dashboard My Collections Index Page


As a user:

- [ ] I can see the number of collections I own in the repository 
- [ ] I can see a button to add a New Collection 
- [ ] I can see several dropdowns to filter through collections 
- [ ] I can see a search bar to search for specific collections 
- [ ] I can see a table listing all collections I have permission to manage 
- [ ] I can see basic information re. each individual collection: 
- [ ] Title 
- [ ] Type 
- [ ] Visibility 
- [ ] Items 
- [ ] Last modified 
- [ ] Actions (View, Edit, Delete, Add to collection)

**Comment by ShanaLMoore** [comment]
Dashboard Collection New Page


As a user:

- [ ]     I can see a form to fill out basic information describing my new Collection
  - [ ]         Title (required)
  - [ ]         Abstract or Summary
- [ ]     I can see a button to display Additional fields for which to further describe my collection
- [ ]     I can see links to Add another input for most descriptors
  - [ ]         I can see links to Remove additional fields
- [ ]     I can see a Save button to create my new collection
- [ ]     I can see a link to Cancel my new Collection and redirect me back to the dashboard my collections index page

**Comment by ShanaLMoore** [comment]
Dashboard Collection Edit Page

As a user:

  

- [ ]   I can see a partial to alter / add to my collection’s descriptors
- [ ]     I can see a dropdown from which I can select a thumbnail for my collection
- [ ]     I can see a button for Additional fields
- [ ]     I can see links to Add another input for most descriptors
  - [ ]         I can see links to Remove additional fields
- [ ]     I can see a button to Save my changes
- [ ]     I can see a link to Cancel my edits, redirecting me to the Dashboard Collection’s show page

**Comment by ShanaLMoore** [comment]
unblocked. retest on: https://demo.hyku-demo.notch8.cloud/

**Comment by ShanaLMoore** [comment]
due to limited resources, we will test and fix the valkyrized version instead
