### ISSUE TITLE
DASHBOARD WORKS Hyku Test Plan

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#75]
# Summary 

Focus on reviewing the test plan for the DASHBOARD WORKS section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks
  - [ ] Dashboard My Works Index Page	39
    - [ ] Dashboard Works New by Batch Page	40
      - [ ] Files	40
      - [ ] Descriptions	41
      - [ ] Relationships	42
      - [ ] Sharing	43
    - [ ] Dashboard Work New Page	44
      - [ ] Descriptions	44
      - [ ] Files	45
      - [ ] Relationships	46
      - [ ] Sharing	47
    - [ ] Dashboard Work Edit Page	48
      - [ ] Descriptions	48
      - [ ] Files	49
      - [ ] Relationships	50
      - [ ] Sharing	51
    - [ ] Review Submissions Page	52
      - [ ] Under Review	52
      - [ ] Published	53
  
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/

**Comment by ShanaLMoore** [comment]
due to limited resources, we will test and fix the valkyrized version instead
