### ISSUE TITLE
USER MANAGEMENT Hyku Test Plan v6.0.0rc1

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#76]
# Summary 

Focus on reviewing the test plan for the USER MANAGEMENT section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks
  - [ ] Manage Users Page	54
  - [ ] Manage Groups Index Page	55
  - [ ] Manage Groups New Page	56
  - [ ] Manage Groups Edit Page	57
    - [ ] Description	57
    - [ ] Users	58
    - [ ] Remove	59
  - [ ] Manage Embargoes Index Page	60
    - [ ] All Active Embargoes	60
    - [ ] Expired Active Embargoes	61
    - [ ] Deactivated Embargoes	62
  - [ ] Manage Embargoes Edit Page	63
  - [ ] Manage Embargoes Deactivate Page	64
  - [ ] Manage Leases Index Page	65
    - [ ] All Active Leases	65
    - [ ] Expired Active Leases	66
    - [ ] Deactivated Leases	67
  - [ ] Manage Leases Edit Page	68
  - [ ] Manage Leases Deactivate Page	69
  
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/
