### ISSUE TITLE
SETTINGS Hyku Test Plan v6.0.0rc1

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#77]
# Summary 

Focus on reviewing the test plan for the SETTINGS section 

ref related parent ticket/epic: 
- #48 

## Acceptance Criteria
- [ ] Create bug tickets for any issues found. 

## Tasks
  - [ ] Settings → Labels PageSettings → Labels Page	70
  - [ ] Settings → Appearance Page	71
    - [ ] Logo / Banner Image	71
    - [ ] Default Images	72
    - [ ] Colors	73
    - [ ] Fonts	74
    - [ ] Custom CSS	75
  - [ ] Settings → Collection Types Index Page	76
  - [ ] Settings → Collection Types New Page	77
  - [ ] Settings → Collection Types Edit Page	78
    - [ ] Description	78
    - [ ] Settings	79
    - [ ] Participants	80
    - [ ] Badge Color	81
  - [ ] Settings → Pages Page	82
  - [ ] Settings → Content Block	83
  - [ ] Settings → Features Page	84
  
## Notes

Test Plan: https://docs.google.com/document/d/1jk29qG4eE69tPbGA9hg5hOCmNRZ77KFN6dTjVV2358g/edit#heading=h.69guibcdizbh

**Comment by ShanaLMoore** [comment]
unblocked. test on: https://demo.hyku-demo.notch8.cloud/

**Comment by ShanaLMoore** [comment]
closing. We will test against and fix the valkyrie branch instead, due to limited resources.
